export default {
//每页显示条数
  pageSize:10,
  //导航权限--管理员/测试成员
  isSuper:{2:'测试人员',1:'管理员'},
  userId:'',
  typeData:[
    {
      type:1,
      label:'非功能测试',
    },
    {
      type:2,
      label:'功能测试',
    },
  ],
  // 非功能测试
  adminMenus:[
    {
      id:1000,
      label:'模拟器类型管理',
      icon:'ios-ionitron',
      path:'type',
      children:[
        {
          id:1001,
          label:'拆包类型管理',
          icon:'',
          path:'unpack'
        },
        {
          id:1002,
          label:'交易识别管理',
          icon:'',
          path:'search'
        },
        {
          id:1003,
          label:'安全组件管理',
          icon:'',
          path:'sec'
        },
        {
          id:1004,
          label:'模拟器类型组装',
          icon:'',
          path:'simu'
        }
      ]
    },
    {
      id:5000,
      label:'模拟器申请',
      icon:'ios-locate',
      path:'taskModel',
      children:[
        {
          id:5001,
          label:'模拟器申请',
          icon:'',
          path:'index'
        }
      ]
    },
    {
      id:2000,
      label:'模拟器实例管理',
      icon:'md-settings',
      path:'caseSetting',
      children:[
        {
          id:2001,
          label:'全部实例',
          icon:'',
          path:'instanceList'
        },
        {
          id:2002,
          label:'已分配实例',
          icon:'',
          path:'instance'
        },
        {
          id:2003,
          label:'待分配申请',
          icon:'',
          path:'applyList'
        },
        {
          id:2004,
          label:'待审核复用申请',
          icon:'',
          path:'repeatApplyList'
        }
      ]
    },
    {
      id:3000,
      label:'模拟器实例配置',
      icon:'ios-stats',
      path:'caseConfig',
      children:[
        {
          id:3001,
          label:'实例参数配置',
          icon:'',
          path:'args'
        },
        {
          id:3002,
          label:'响应报文管理',
          icon:'',
          path:'message'
        },
        {
          id:3003,
          label:'参数文件管理',
          icon:'',
          path:'argsFile'
        },
        {
          id:3004,
          label:'延迟时间配置',
          icon:'',
          path:'scene'
        },
        {
          id:3005,
          label:'运行统计',
          icon:'',
          path:'statistics'
        },
        {
          id:3006,
          label:'日志监控',
          icon:'',
          path:'logs'
        }
      ]
    },
    {
      id:4000,
      label:'系统管理',
      icon:'logo-windows',
      path:'setting',
      children:[
        {
          id:4001,
          label:'机器管理',
          icon:'',
          path:'machine'
        },
        {
          id:4002,
          label:'KMC管理',
          icon:'',
          path:'kmc'
        },
        {
          id:4003,
          label:'人员管理',
          icon:'',
          path:'user'
        },
        {
          id:4004,
          label:'插件管理',
          icon:'',
          path:'plugin'
        }
      ]
    },
    {
      id:6000,
      label:'个人&操作手册',
      icon:'md-contact',
      path:'other',
      children:[
        {
          id:6001,
          label:'个人信息管理',
          icon:'',
          path:'userMessage'
        },
        {
          id:6002,
          label:'操作手册',
          icon:'',
          path:'manual'
        }
      ]
    }
  ],
  managerMenus:[
    {
      id:1000,
      label:'模拟器申请',
      icon:'ios-locate',
      path:'taskModel',
      children:[
        {
          id:1001,
          label:'模拟器申请',
          icon:'',
          path:'index'
        }
      ]
    },
    {
      id:2000,
      label:'模拟器实例配置',
      icon:'ios-stats',
      path:'caseConfig',
      children:[
        {
          id:3001,
          label:'实例参数配置',
          icon:'',
          path:'args'
        },
        {
          id:3002,
          label:'响应报文管理',
          icon:'',
          path:'message'
        },
        {
          id:3003,
          label:'参数文件管理',
          icon:'',
          path:'argsFile'
        },
        {
          id:3004,
          label:'延迟时间配置',
          icon:'',
          path:'scene'
        },
        {
          id:3005,
          label:'运行统计',
          icon:'',
          path:'statistics'
        },
        {
          id:3006,
          label:'日志监控',
          icon:'',
          path:'logs'
        }
      ]
    },
    {
      id:6000,
      label:'个人&操作手册',
      icon:'md-contact',
      path:'other',
      children:[
        {
          id:6001,
          label:'个人信息管理',
          icon:'',
          path:'userMessage'
        },
        {
          id:6002,
          label:'操作手册',
          icon:'',
          path:'manual'
        }
      ]
    }
  ],
  // 功能测试
  adminMenusFt:[
    {
      id:1000,
      label:'模拟器类型管理',
      icon:'ios-ionitron',
      path:'type',
      children:[
        {
          id:1001,
          label:'拆包类型管理',
          icon:'',
          path:'unpack'
        },
        {
          id:1002,
          label:'交易识别管理',
          icon:'',
          path:'search'
        },
        {
          id:1003,
          label:'安全组件管理',
          icon:'',
          path:'sec'
        },
        {
          id:1004,
          label:'模拟器类型组装',
          icon:'',
          path:'simu'
        }
      ]
    },
    {
      id:5000,
      label:'模拟器申请',
      icon:'ios-locate',
      path:'taskModel',
      children:[
        {
          id:5001,
          label:'模拟器申请',
          icon:'',
          path:'index'
        }
      ]
    },
    {
      id:2000,
      label:'模拟器实例管理',
      icon:'md-settings',
      path:'caseSetting',
      children:[
        {
          id:2001,
          label:'全部实例',
          icon:'',
          path:'instanceList'
        },
        {
          id:2002,
          label:'已分配实例',
          icon:'',
          path:'instance'
        },
        {
          id:2003,
          label:'待分配申请',
          icon:'',
          path:'applyList'
        },
        {
          id:2004,
          label:'待审核复用申请',
          icon:'',
          path:'repeatApplyList'
        }
      ]
    },
    {
      id:3000,
      label:'模拟器实例配置',
      icon:'ios-stats',
      path:'caseConfig',
      children:[
        {
          id:3001,
          label:'实例参数配置',
          icon:'',
          path:'args'
        },
        {
          id:3002,
          label:'响应报文管理',
          icon:'',
          path:'message'
        },
        {
          id:3003,
          label:'参数文件管理',
          icon:'',
          path:'argsFile'
        },
        {
          id:3006,
          label:'日志监控',
          icon:'',
          path:'logs'
        },
        {
          id:3007,
          label:'执行历史',
          icon:'',
          path:'history'
        }
      ]
    },
    {
      id:4000,
      label:'系统管理',
      icon:'logo-windows',
      path:'setting',
      children:[
        {
          id:4001,
          label:'机器管理',
          icon:'',
          path:'machine'
        },
        {
          id:4002,
          label:'KMC管理',
          icon:'',
          path:'kmc'
        },
        {
          id:4003,
          label:'人员管理',
          icon:'',
          path:'user'
        },
        {
          id:4004,
          label:'插件管理',
          icon:'',
          path:'plugin'
        }
      ]
    },
    {
      id:6000,
      label:'个人&操作手册',
      icon:'md-contact',
      path:'other',
      children:[
        {
          id:6001,
          label:'个人信息管理',
          icon:'',
          path:'userMessage'
        },
        {
          id:6002,
          label:'操作手册',
          icon:'',
          path:'manual'
        }
      ]
    }
  ],
  managerMenusFt:[
    {
      id:1000,
      label:'模拟器申请',
      icon:'ios-locate',
      path:'taskModel',
      children:[
        {
          id:1001,
          label:'模拟器申请',
          icon:'',
          path:'index'
        }
      ]
    },
    {
      id:2000,
      label:'模拟器实例配置',
      icon:'ios-stats',
      path:'caseConfig',
      children:[
        {
          id:3001,
          label:'实例参数配置',
          icon:'',
          path:'args'
        },
        {
          id:3002,
          label:'响应报文管理',
          icon:'',
          path:'message'
        },
        {
          id:3003,
          label:'参数文件管理',
          icon:'',
          path:'argsFile'
        },
        {
          id:3004,
          label:'延迟时间配置',
          icon:'',
          path:'scene'
        },
        {
          id:3005,
          label:'运行统计',
          icon:'',
          path:'statistics'
        },
        {
          id:3006,
          label:'日志监控',
          icon:'',
          path:'logs'
        },
        {
          id:3007,
          label:'执行历史',
          icon:'',
          path:'history'
        }
      ]
    },
    {
      id:6000,
      label:'个人&操作手册',
      icon:'md-contact',
      path:'other',
      children:[
        {
          id:6001,
          label:'个人信息管理',
          icon:'',
          path:'userMessage'
        },
        {
          id:6002,
          label:'操作手册',
          icon:'',
          path:'manual'
        }
      ]
    }
  ],
  //实例管理--已分配实例状态
  instanceState:{8:'已分配',1:'申请中',9:'已回收',4:'已删除'},
  //申请
  applyState:{8:'已分配',1:'申请中',9:'已回收',4:'已保存'},
  //实例参数配置
  ArgsSecTypeData:{1:'空安全报文头',2:'采用新一代加解密框架'},
  headTypeData:{1:'类Http报文头',2:'Bin类型（P6）'},
  //启动、停止、确认命令
  secCmdData:{start:1,stop:2,confirm:4},
  //延迟策略
  // scenePolicy:{0:'全局延迟',1:'根据交易码进行延迟',2:'根据系统交易号进行延迟',3:'根据安全节点进行延迟'},
  scenePolicy:{
    1:{name:'全局延迟',visible:false},
    2:{name:'根据交易码进行延迟',visible:true,label:'交易码'},
    3:{name:'根据系统交易号进行延迟',visible:true,label:'系统交易号'},
    4:{name:'根据安全节点进行延迟',visible:true,label:'安全节点'}
  },
  sceneListState:[
    {value:true,label:'启用'},
    {value:false,label:'禁用'},
  ],

  //参数文件类型码
  argsFileStateData:[
    {
      code:1,
      name:'关联文件'
    },
    {
      code:2,
      name:'参数文件'
    },
  ],
  //机器管理状态
  machineState:{0:'停止',1:'正常'},


  //编辑状态
  editState:{
    commit:1,//提交
    save:4//保存
  },

   //实例参数用到
  adapterTypeData:{
    'Http':'http',
    'TcpShort':'tcp',
    'TcpLong(FixLen)':'tcp',
    'TcpLong(Len)':'tcp',
    'TcpLong(Sep)':'tcp',
    'ActiveMQ':'ActiveMQ',
    'WebShpereMQ':'WebShpereMQ',
  },

  //安全类型
  secTypeData:{
    'CSSP':'CSSP',
    'DCC':'DCC',
    '新一代安全':'新一代安全',
  },
  messageIsDyn:{
    1:'动态',
    2:"静态"
  },
  //响应文件--替换规则--日期格式
  messageRuleDateType:[
    {value:1,label:'yyyy-MM-dd'},
    {value:2,label:'yyyyMMdd'},
    {value:3,label:'MM/dd/yyyy'},
    {value:4,label:'HHmmss'},
    {value:5,label:'HH:mm:ss'},
    {value:6,label:'yyyy-MM-dd HH:mm:ss'},
    {value:7,label:'yyyy-MM-dd HH:mm:ss.S'},
    {value:8,label:'yyyyMMddHHmmss'},
    {value:9,label:'yyyyMMddHHmmssS'}
  ],
  pluginTypeData:{
    "sys":'系统级插件',"comType":'通讯类型插件',"sysType":'系统类型插件',"secType":"安全类型插件"
  },

   validateSequence : (rule, value, callback) => {
    let regNum = /^.{1,5}$/;
    if (value === '') {
      callback(new Error('输入排序(升序)'));
    } else if (!Number.isInteger(+value)) {
      callback(new Error('输入数字'));
    } else if (!regNum.test(value)) {
      callback(new Error('长度过长'));
    } else {
      callback();
    }
  },
}
